//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeerReview.MvcHotel.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PeerReview.MvcHotel.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Answers_Action_Delete {
            get {
                return ResourceManager.GetString("Answers_Action_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Answers_Action_Edit {
            get {
                return ResourceManager.GetString("Answers_Action_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Answer.
        /// </summary>
        public static string Answers_Add {
            get {
                return ResourceManager.GetString("Answers_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Answers_Col_Date {
            get {
                return ResourceManager.GetString("Answers_Col_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string Answers_Col_Id {
            get {
                return ResourceManager.GetString("Answers_Col_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string Answers_Col_Item {
            get {
                return ResourceManager.GetString("Answers_Col_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Answers_Col_Question {
            get {
                return ResourceManager.GetString("Answers_Col_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Answers_Col_Value {
            get {
                return ResourceManager.GetString("Answers_Col_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Answer.
        /// </summary>
        public static string Answers_Create_Title {
            get {
                return ResourceManager.GetString("Answers_Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Answer.
        /// </summary>
        public static string Answers_Edit_Title {
            get {
                return ResourceManager.GetString("Answers_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Answers.
        /// </summary>
        public static string Answers_Title {
            get {
                return ResourceManager.GetString("Answers_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PeerReview Hotel.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        public static string Assignments_Action_Activate {
            get {
                return ResourceManager.GetString("Assignments_Action_Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate.
        /// </summary>
        public static string Assignments_Action_Deactivate {
            get {
                return ResourceManager.GetString("Assignments_Action_Deactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute.
        /// </summary>
        public static string Assignments_Bulk_Execute {
            get {
                return ResourceManager.GetString("Assignments_Bulk_Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question IDs (comma separated).
        /// </summary>
        public static string Assignments_Bulk_QuestionIds {
            get {
                return ResourceManager.GetString("Assignments_Bulk_QuestionIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk Assign.
        /// </summary>
        public static string Assignments_Bulk_Title {
            get {
                return ResourceManager.GetString("Assignments_Bulk_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User IDs (comma separated).
        /// </summary>
        public static string Assignments_Bulk_UserIds {
            get {
                return ResourceManager.GetString("Assignments_Bulk_UserIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Assignments_Col_Active {
            get {
                return ResourceManager.GetString("Assignments_Col_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string Assignments_Col_Id {
            get {
                return ResourceManager.GetString("Assignments_Col_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Assignments_Col_Question {
            get {
                return ResourceManager.GetString("Assignments_Col_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string Assignments_Col_User {
            get {
                return ResourceManager.GetString("Assignments_Col_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By question.
        /// </summary>
        public static string Assignments_Filter_ByQuestion {
            get {
                return ResourceManager.GetString("Assignments_Filter_ByQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By user.
        /// </summary>
        public static string Assignments_Filter_ByUser {
            get {
                return ResourceManager.GetString("Assignments_Filter_ByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Assignments_Show {
            get {
                return ResourceManager.GetString("Assignments_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignments.
        /// </summary>
        public static string Assignments_Title {
            get {
                return ResourceManager.GetString("Assignments_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Btn_Back {
            get {
                return ResourceManager.GetString("Btn_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Btn_Save {
            get {
                return ResourceManager.GetString("Btn_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate?.
        /// </summary>
        public static string Confirm_Activate {
            get {
                return ResourceManager.GetString("Confirm_Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate?.
        /// </summary>
        public static string Confirm_Deactivate {
            get {
                return ResourceManager.GetString("Confirm_Deactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete?.
        /// </summary>
        public static string Confirm_Delete {
            get {
                return ResourceManager.GetString("Confirm_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions.
        /// </summary>
        public static string Dashboard_Questions {
            get {
                return ResourceManager.GetString("Dashboard_Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Dashboard_Users {
            get {
                return ResourceManager.GetString("Dashboard_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Field_Category {
            get {
                return ResourceManager.GetString("Field_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Field_Description {
            get {
                return ResourceManager.GetString("Field_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuestionId.
        /// </summary>
        public static string Field_QuestionId {
            get {
                return ResourceManager.GetString("Field_QuestionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuestionItemId.
        /// </summary>
        public static string Field_QuestionItemId {
            get {
                return ResourceManager.GetString("Field_QuestionItemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Field_Title {
            get {
                return ResourceManager.GetString("Field_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Field_Value {
            get {
                return ResourceManager.GetString("Field_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العربية.
        /// </summary>
        public static string Lang_Arabic {
            get {
                return ResourceManager.GetString("Lang_Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Lang_English {
            get {
                return ResourceManager.GetString("Lang_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed.
        /// </summary>
        public static string Login_Failed {
            get {
                return ResourceManager.GetString("Login_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login_Submit {
            get {
                return ResourceManager.GetString("Login_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string Login_UserName {
            get {
                return ResourceManager.GetString("Login_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignments.
        /// </summary>
        public static string Menu_Assignments {
            get {
                return ResourceManager.GetString("Menu_Assignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Menu_Dashboard {
            get {
                return ResourceManager.GetString("Menu_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Menu_Login {
            get {
                return ResourceManager.GetString("Menu_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Menu_Logout {
            get {
                return ResourceManager.GetString("Menu_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Answers.
        /// </summary>
        public static string Menu_MyAnswers {
            get {
                return ResourceManager.GetString("Menu_MyAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions.
        /// </summary>
        public static string Menu_Questions {
            get {
                return ResourceManager.GetString("Menu_Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Menu_Users {
            get {
                return ResourceManager.GetString("Menu_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activated successfully..
        /// </summary>
        public static string Msg_Activated {
            get {
                return ResourceManager.GetString("Msg_Activated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved successfully..
        /// </summary>
        public static string Msg_Added {
            get {
                return ResourceManager.GetString("Msg_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivated successfully..
        /// </summary>
        public static string Msg_Deactivated {
            get {
                return ResourceManager.GetString("Msg_Deactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted successfully..
        /// </summary>
        public static string Msg_Deleted {
            get {
                return ResourceManager.GetString("Msg_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated successfully..
        /// </summary>
        public static string Msg_Updated {
            get {
                return ResourceManager.GetString("Msg_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded successfully..
        /// </summary>
        public static string Msg_Uploaded {
            get {
                return ResourceManager.GetString("Msg_Uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Msg_Welcome {
            get {
                return ResourceManager.GetString("Msg_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Questions_Action_Delete {
            get {
                return ResourceManager.GetString("Questions_Action_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Questions_Action_Edit {
            get {
                return ResourceManager.GetString("Questions_Action_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Question.
        /// </summary>
        public static string Questions_Add {
            get {
                return ResourceManager.GetString("Questions_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Questions_Col_Description {
            get {
                return ResourceManager.GetString("Questions_Col_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string Questions_Col_Id {
            get {
                return ResourceManager.GetString("Questions_Col_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string Questions_Col_Items {
            get {
                return ResourceManager.GetString("Questions_Col_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Questions_Col_Title {
            get {
                return ResourceManager.GetString("Questions_Col_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Question.
        /// </summary>
        public static string Questions_Create_Title {
            get {
                return ResourceManager.GetString("Questions_Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Question.
        /// </summary>
        public static string Questions_Edit_Title {
            get {
                return ResourceManager.GetString("Questions_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions.
        /// </summary>
        public static string Questions_Title {
            get {
                return ResourceManager.GetString("Questions_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Status_Active {
            get {
                return ResourceManager.GetString("Status_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string Status_Inactive {
            get {
                return ResourceManager.GetString("Status_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string Upload_File_File {
            get {
                return ResourceManager.GetString("Upload_File_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Upload_File_Submit {
            get {
                return ResourceManager.GetString("Upload_File_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload a file.
        /// </summary>
        public static string Upload_File_Title {
            get {
                return ResourceManager.GetString("Upload_File_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        public static string Users_Action_Activate {
            get {
                return ResourceManager.GetString("Users_Action_Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate.
        /// </summary>
        public static string Users_Action_Deactivate {
            get {
                return ResourceManager.GetString("Users_Action_Deactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Users_Action_Delete {
            get {
                return ResourceManager.GetString("Users_Action_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Users_Action_Edit {
            get {
                return ResourceManager.GetString("Users_Action_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + User.
        /// </summary>
        public static string Users_Add {
            get {
                return ResourceManager.GetString("Users_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        public static string Users_Col_FullName {
            get {
                return ResourceManager.GetString("Users_Col_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string Users_Col_Id {
            get {
                return ResourceManager.GetString("Users_Col_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Users_Col_Role {
            get {
                return ResourceManager.GetString("Users_Col_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Users_Col_Status {
            get {
                return ResourceManager.GetString("Users_Col_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Users_Col_UserName {
            get {
                return ResourceManager.GetString("Users_Col_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users_Title {
            get {
                return ResourceManager.GetString("Users_Title", resourceCulture);
            }
        }
    }
}
